### ISSUE TITLE
Files under the WEB-INF directory are directly accessible in a default installation

### ISSUE THREAD

**Issue by jackdos** [iipc/openwayback#353] opened 2017-08-24 17:15 UTC
When creating a completely clean default installation of the openwayback web application, it is possible to get access to files in the WEB-INF directory by browsing to directly to the URLs of the form:

http://server:port/wayback/WEB-INF/web.xml
http://server:port/wayback/WEB-INF/classes/logging.properties 

The WEB-INF directory is supposed to be restricted by default as it contains details of the application configuration which could potentially be a leak of sensitive information.

This affects installing both as the ROOT and as a non-root application. For the non-root, use URLs of the form:

http://server:port/context/wayback/WEB-INF/web.xml
http://server:port/context/wayback/WEB-INF/classes/logging.properties

This was seen using a standard CentOS7 minimal install, installing tomcat 7 with "yum install tomcat", then using the installation instructions on the openwayback wiki to install the 2.3.2 release.

**Comment by kris-sigur** [comment] 2017-08-25 08:49
Confirmed.

What's happening is that OWB is capturing any request to \<contextroot\>/wayback/\<anything\>.

If "anything" matches a replay URI (e.g. starts with a timestamp) it gets redirected into replay rendering.

**Everything** else gets mapped onto the root of the `webapp` folder. This allows access to search pages, banner resources etc. 

Unfortunately, this includes the WEB-INF folder, and not by accident. This is actually needed to serve the JSP etc. stored under WEB-INF.

The best option I can see is to put in a black list of resources that aren't allowed to be served in this manner in place. 

My suggested blacklist:

```
WEB-INF/lib
WEB-INF/classes
WEB-INF/*.xml
```

Implemented this might look something like: https://github.com/iipc/openwayback/pull/354 

I'm aware that this is a hack-y fix. But a proper fix would likely require throwing out OWB entire 'controller' framework and replacing it with something more sensible (like Spring MVC perhaps).

**Comment by jackdos** [comment] 2017-08-25 09:21
Thanks for looking at this so quickly. I appreciate the proposed solution coming in so soon.

I agree that the proper fix would probably involve a fairly substantial re-write using a more standard MVC framework, which doesn't seem like a bad idea, although I appreciate that it will probably be fairly time-consuming. Rolling your own frameworks does come with the danger of missing things like this. 

However, even a more "hack-y" patch like your suggestion should probably work from a whitelist rather than blacklist principle. This would be more in line with what you would get from an MVC framework like Spring where you have to configure your application to explicitly map the URLs that you want to expose.

I would feel more comfortable if you whitelisted the jsps and images that you need to expose rather than blacklist files you don't want to expose. Using a blacklist, if you add a new file at some point in the future that isn't covered by the blacklist, then it is exposed by default, this is the kind of thing that can sit un-noticed for a long time. Using a whitelist, if you add a new file at some point it is hidden by default, and if you need it to be exposed it will be obvious pretty quickly if you forget to whitelist it.

**Comment by kris-sigur** [comment] 2017-08-25 09:40
The problem with a white list is that there may be cases where someone has extended Wayback and added additional resources under WEB-INF. At a minimum, the use of a white list means making the list easily configurable, which is more code.

That said, if someone wants to write up a bit more comprehensive solution using a white list, I wont object!

**Comment by jackdos** [comment] 2017-08-25 09:46
Agreed. Of course a blacklist also potentially has this problem if the resource added needs some extra configuration, which the user assumes is protected by default as it's in the WEB-INF folder. It is arguably even more likely that the config would contain sensitive information (external server credentials for example) if it was part of an extension than the default configuration files.

In either case, user configurable lists seem necessary, and documentation that if you are extending the functionality, you have to be aware of this.

**Comment by ldko** [comment] 2017-08-25 17:14
@kris-sigur, regarding the [comment](https://github.com/iipc/openwayback/issues/353#issuecomment-324860747):
```
Unfortunately, this includes the WEB-INF folder, and not by accident. This is actually needed to serve the JSP etc. stored under WEB-INF.
```
Based on something I saw in the [Wayback 1.4.0 release notes](https://github.com/iipc/openwayback/blob/master/src/site/markdown/release_notes.md#release-140) that says "Changed locations of replay, query, and exception .jsp files within .war file to underneath WEB-INF, so they are not directly accessible via HTTP" I was thinking it was not intentional in OpenWayback that files under WEB-INF are directly accessible.

Before seeing #354 I had put something like this in my local web.xml file:

```
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>precluded methods</web-resource-name>
            <url-pattern>/wayback/WEB-INF/*</url-pattern>
        </web-resource-collection>
        <auth-constraint/>
    </security-constraint>
```
as a temporary fix to prevent the content under WEB-INF being directly accessible via http, and it seemed to work without breaking the application--though because this is blocking access via a URL pattern it has to be done for every access point. I am not proposing this as a solution since as far as I know it would have to be done for every access point created and seems hacky, but being able to block access to the WEB-INF content this way with the application still seeming to function properly made me wonder about whether the WEB-INF does need to be at all public.

Perhaps this doesn't make a difference anyway in regard to what you are describing is the overall problem and as far as having to change a lot of code to fix the issue, in which case I can test out the changes in #354. I just wanted to bring it up.

**Comment by ldko** [comment] 2017-08-30 16:07
Closing per #354

**Closed by ldko** 2017-08-30 16:07 UTC
