### ISSUE TITLE
UI Localisation

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#46] opened 2013-12-18 10:45 UTC
**S'sheet line:** 29
**For whom?** BNF, NULI, BL, DN
**Notes:** There are holes, but framework ok. How to review? Consider switch to JSTL?
**Est. Milestone:** 2.0.x

**Comment by kris-sigur** [comment] 2015-02-27 12:19
While a switch to JSTL was suggested, I think, in order to close this, it would be sufficient to ensure that all text strings are read from a properties file and that any dates use a date format read also from the properties file.

**Comment by RogerMathisen** [comment] 2015-05-13 06:59
I have gone through the JSP files in the project, and hope to have moved out most of the hard coded text strings. During testing I encountered a problem with national characters (ie. chars with ascii value > 127).  The properties class used for loading the WaybackUI_<nls>.properties uses by default ISO 8859-1 character set. Since the project uses UTF-8 by default, ascii values > 127 will be displayed incorrectly in the GUI. This can be fixed in a number of ways.

1. Use ISO 8859-1 for the WaybackUI_<nls>.properties: This might be cumbersome to maintain, as one will need to remember to save this single file in another character encoding than the rest of the project.
2. Use unicode escapes: From the JAVA API DOC "Unicode escapes as defined in section 3.3 of The Java™ Language Specification. " This will lead to poorly readable WaybackUI_<nls>.properties, and will make the process of creating new NLS stings more difficult.
3. Modify StringFormatter: I have made a modification in the getLocalized() method in StringFormatter using "new String(retVal.getBytes("ISO-8859-1"), "UTF-8")". This will make it possible to write the .properties files in UTF-8 and have the NLS characters display correctly in the GUI.

Looking for feedback on which method should be used.

**Comment by RogerMathisen** [comment] 2015-05-13 07:08
I have made a WaybackUI_\<nls\>.properties with all UI strings replaced with "*" characters. This file is useful for testing to "smoke out" the strings that are still hard coded in the UI files. I could supply this file for testing by others, but I don't want to include it into the source code. Where would be the natural place to put it?

**Comment by kris-sigur** [comment] 2015-05-13 09:10
@RogerMathisen Load the properties files as UTF-8 files. 

`new String(retVal.getBytes("ISO-8859-1"), "UTF-8")` seems hacky though. Could you point at the parts of the code where this is happening?

**Comment by RogerMathisen** [comment] 2015-05-13 09:30
In the org.archive.wayback.util.StringFormatter

The original method: 

public String getLocalized(String key) {
		if (bundle != null) {
			try {
				return bundle.getString(key);
			} catch (Exception e) {
			}
		}
		return key;
	}

**Comment by kris-sigur** [comment] 2015-05-13 09:48
I see. It's basically this issue: https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle

I'd rather do the Control subclass. Feels less brittle. Anyone else have thoughts? @PsypherPunk @anjackson

**Comment by RogerMathisen** [comment] 2015-05-13 09:53
Yeah, but that's a little more work. If we go that route we might need to move this issue to 2.3.0?

**Comment by kris-sigur** [comment] 2015-05-13 11:37
Doesn't seem like that big a task to me. Sketched it out here: https://github.com/iipc/openwayback/compare/iipc:master...kris-sigur:PropUTF8?expand=1

Seems to work as intended.

**Comment by RogerMathisen** [comment] 2015-05-13 14:28
I tested the code and it seems to work fine. The only thing is that most (if not all?) of the .JSP files use the deprecated WaybackRequest.getFormatter() instead of UIResults.getFormatter(), so we either need to: Add the same change to WaybackRequest as you did to UIResults or alter the JSP-files to use UIResults.

Option two is probably the best, but it takes a little time to do.

**Comment by kris-sigur** [comment] 2015-05-13 14:32
Yes, I know, I edited WaybackRequest as well.

**Comment by RogerMathisen** [comment] 2015-05-15 11:13
Could you please a pull request for this so we get it into the 2.2.0 release?

**Comment by kris-sigur** [comment] 2015-05-15 11:56
@RogerMathisen Its best to include it with your changes. What I could do is make a pull request to the branch where you are working on the UI localizations. That would make it super easy for you to incorporate my changes. Just point me at your working branch.

**Comment by RogerMathisen** [comment] 2015-05-15 12:07
I have your changes in my branch for testing purposes, but was reluctant to create a pull request with them included in fear it would mess things up. If you don't do anything I can just keep them all and create a pull request.

**Comment by kris-sigur** [comment] 2015-05-15 12:31
@RogerMathisen That's perfectly fine by me.

**Closed** 2015-05-28 15:11 UTC
Labels: enhancement

**Comment by isido** [comment] 2015-06-16 13:20
I've tried to use this, but it's not quite clear from the documentation how. What do I need to do besides providing WaybackUI_fi.properties file (for Finnish) and setting the browser's language preference accordingly? (Pardon my lack of java webapp-fu)

**Comment by RogerMathisen** [comment] 2015-06-17 06:42
Just put your modified language file under WEB-INF/classes alongside the original WaybackUI.properties and you should be all set.

**Comment by RogerMathisen** [comment] 2015-06-17 07:03
Just put your modified language file under WEB-INF/classes alongside the original WaybackUI.properties. Also you might have to look into the language settings your web server is running under.

I'm using Tomcat and Linux, and need to set the LANG environment variable. When I have both the original and the modified WaybackUI_nb_NO.properties the settings:

LANG=nb_NO.UTF-8 Gives the Norwegian translation.
LANG=en_US.UTF-8 Gives the text from the original WaybackUI.properties

**Comment by anjackson** [comment] 2015-06-17 09:33
If you want to run multiple access points with different languages, you can do this (which we do to support Welsh):

```
  <!-- Welsh front-end -->
 <bean name="wayback-cy" parent="wayback">
    <property name="accessPointPath" value="${wayback.port}:archive-cy"/>
  <property name="locale">
   <bean class="java.util.Locale">
    <!-- cy_GB -->
    <constructor-arg type="java.lang.String" value="cy" />
    <constructor-arg type="java.lang.String" value="GB" />
   </bean>
  </property>

    <property name="replayPrefix" value="${wayback.urlprefix}archive-cy/" />
    <property name="queryPrefix" value="${wayback.urlprefix}archive-cy/" />
    <property name="staticPrefix" value="${wayback.urlprefix}archive-cy/" />

  <property name="uriConverter">
   <bean class="org.archive.wayback.archivalurl.ArchivalUrlResultURIConverter">
      <property name="replayURIPrefix" value="${wayback.urlprefix}archive-cy/"/>
   </bean>
  </property>
 </bean>
```

You might also want to consider installing the ICU4J package into your JRE, if you need localisation support for dates in a language that is not supported by the base Java install (again, for us, this is Welsh).

* http://userguide.icu-project.org/icu4j-locale-service-provider#TOC-Using-ICU4J-Locale-Service-Provider

**Comment by isido** [comment] 2015-06-17 09:46
Thanks. My issue is probably somewhere in my overlay build process as the correct resource file is not getting copied to the classpath, but I'll keep looking into it. I'm trying to put together a rather minimal overlay example, and localization is one of the things I'd like to include: https://github.com/NatLibFi/openwayback-overlay-example

**Comment by RogerMathisen** [comment] 2015-06-17 11:07
I updated the Wiki with the basic set up. 

https://github.com/iipc/openwayback/wiki/NLS-configuration

We should definitely consider adding the info Andy provided, as I think it might be very helpful for users wanting this kind of functionality.
