### ISSUE TITLE
How to delete data

### ISSUE THREAD

**Issue by mtcjayne** [iipc/openwayback#377] opened 2018-04-29 03:47 UTC
How does a person delete the site data from an OpenWayback installation? I'd like to wipe mine but apparently just deleting the `webapps/ROOT` directory and `webapps/ROOT.war` file is not enough.

**Comment by ldko** [comment] 2018-04-30 18:44
Hi @mtcjayne ,
I'm not sure if I know what you are asking. Tomcat does has a `work/` directory where files used at run time are cached. To get rid of that cache you can (stop OpenWayback or Tomcat if OpenWayback is running) delete the directory for your OpenWayback's cached files at `$CATALINA_HOME/work/Catalina/localhost/_owb_deploy_name_` where `$CATALINA_HOME` is your Tomcat installation .

If that is not what you are referring to, can you provide further details of what you are wanting to accomplish and what the problem is you are seeing?

Thanks!

**Comment by ldko** [comment] 2018-04-30 21:02
Ok, so you were asking about the WARC data/archived websites that show up/are indexed in OpenWayback. By default, OpenWayback uses the BDB Index, and in wayback.xml the values set for the variables `wayback.archivedir.1` and `wayback.archivedir.2` indicate what directories OpenWayback will look in for WARC files to be added to the index when you start OpenWayback. This happens via the variables being used in the `WEB-INF/BDBCollection.xml` configuration file at:

```
        <bean class="org.archive.wayback.resourcestore.resourcefile.DirectoryResourceFileSource">
          <property name="name" value="files1" />
          <property name="prefix" value="${wayback.archivedir.1}" />
          <property name="recurse" value="false" />
        </bean>
```
If you deleted the ROOT and ROOT.war, the WARC files would persist as long as you hadn't changed your base directory to be inside of ROOT, and if you continue using the same directories for  `wayback.archivedir.1` and `wayback.archivedir.2` with the WARCs still in them, yes they will continue to show up in the index. When you deleted your WARC files, they were no longer in the location to be indexed, so they would no longer be available in OpenWayback.

I am going to close this because you seem to have figured this issue out. You can re-open it if that isn't the case. Thank you!

**Closed by ldko** 2018-04-30 21:02 UTC

**Comment by mtcjayne** [comment] 2018-04-30 21:13
Yep, that's what I'd needed. Thanks for the confirmation.
